***Jess's Intro College Math Notes-***    
- - -   

HW 5.3.2-  
**find tableau changing ratios:** 

In [7]:
import numpy as np

B = np.array([[2, 1, 4], [7,1,7], [6,3,1]])  # values from #1

for value in [1, 2]: # get ratio for second and third changing rows
    p = (0,1)  # B[p] is the pivot value
    c = value  # B[c,] is the changing row
    mx = -B[c, p[1]] / B[p]
    print('multiplier for changing row ' + str(c) + ' {row = ' + str(B[c,]) +
          '}\n...to create a zero = ' + str(mx))


multiplier for changing row 1 {row = [7 1 7]}
...to create a zero = -1.0
multiplier for changing row 2 {row = [6 3 1]}
...to create a zero = -3.0


***maximize LP problem using the initial tableau thing approach***
    
*pivot value appears to be smallest cell > 1 in col with smallest value (-6) thus far*      

In [8]:
import numpy as np

s = np.array([2,8,3,1,0,0,12])
t = np.array([3,2,0,0,1,0,20])
p = np.array([-6,-1,-3,0,0,1,0])
init = np.array([s,t,p])  #  using names s,t,p as labeled in HW

pxy = (0,0)
pval = 2
prow = init[pxy[0]]

for r in range(len(init)):
    print(init[r] + (prow * -(init[r][pxy[1]] / pval)))
    print('\n\n')
# (row of zeros is the prow, it does not actually get changed)

# another example :
s = np.array([9,3,1,1,0,0,15])
t = np.array([1,7,2,0,1,0,20])
p = np.array([-1,-2,-5,0,0,1,0])
init = np.array([s,t,p])

pxy = (1,2)
pval = 2
prow = init[pxy[0]]

for r in range(len(init)):
    print(init[r] + (prow * -(init[r][pxy[1]] / pval)))
    print('\n\n')


[0. 0. 0. 0. 0. 0. 0.]



[  0.  -10.   -4.5  -1.5   1.    0.    2. ]



[ 0. 23.  6.  3.  0.  1. 36.]



[ 8.5 -0.5  0.   1.  -0.5  0.   5. ]



[0. 0. 0. 0. 0. 0. 0.]



[ 1.5 15.5  0.   0.   2.5  1.  50. ]





``` python3
def void_pulp():  # Perhaps a pulp method too
    import pulp as p
    # initialize some PuLP variables:
    prob = p.LpProblem('prob', p.LpMaximize)
    x = p.LpVariable("x", lowBound=0)  # Create a variable x >=
    y = p.LpVariable("y", lowBound=0)
    
    
    def lpMax(goal, inputs, prob):
        prob += goal
        for equ in inputs:
            prob += equ
        prob.solve()
        results = {}
        # results['prob'] = prob
        for var in prob.variables():
            results[var] = var.varValue
        results['optimal'] = p.value(prob.objective)
        return results
    
    # example values:
    goal = x + (2 * y)
    inputs = [y <= 4 * x, y >= .25 * x, y <= 5 - x]
    
    # run:
    results = lpMax(goal, inputs, prob)
    print(str('Results:\n' + str(results)))
```

***matrix multiplication / operations with matrix inverse "I":***

In [10]:
import numpy as np

ex_A = np.array([[1,7],[-4,-26]])
ex_B = np.array([[1,-6],[5,-28]])

def matrix_ops(A=ex_A, B=ex_B):
    try:
        AinvB = np.dot(np.linalg.inv(A), B)
        print('A-1B =\n' + str(AinvB))
    except:
        print('Could not calculate A-1B')       
    try:
        BinvA = np.dot(np.linalg.inv(B), A)
        print('B-1A =\n' + str(BinvA))
    except:
        print('Could not calculate B-1A, continuing...')
    try:
        ABinv = np.linalg.inv(np.matmul(A,B))
        print('(AB)-1 =\n' + str(ABinv))
    except:
        print('Could not calculate (AB)-1, continuing...')
    try:
        AinvBinv = np.dot(np.linalg.inv(A), np.linalg.inv(B))
        print('A-1*B-1 =\n' + str(AinvBinv))
    except:
        print('Could not calculate A-1*B-1, continuing...')
    print('\n Completed matrix operations for matrices A and B! \n\n')

# run: #
# matrix_ops()  # using example values

# more examples, testing w/ random matrices:

def evalrandom():
    def randmat() : return np.random.randint(1,3,(3,3))
    for i in range(5):
        print(str('\nRunning random matrix example ' + str(i) + ' of 5..\n'))
        matrix_ops(randmat(), randmat()) 

# run with:
evalrandom()


Running random matrix example 0 of 5..

Could not calculate A-1B
Could not calculate B-1A, continuing...
(AB)-1 =
[[-5.62949953e+14 -5.62949953e+14  8.44424930e+14]
 [ 3.75299969e+14  3.75299969e+14 -5.62949953e+14]
 [ 3.75299969e+14  3.75299969e+14 -5.62949953e+14]]
Could not calculate A-1*B-1, continuing...

 Completed matrix operations for matrices A and B! 



Running random matrix example 1 of 5..

Could not calculate A-1B
Could not calculate B-1A, continuing...
Could not calculate (AB)-1, continuing...
Could not calculate A-1*B-1, continuing...

 Completed matrix operations for matrices A and B! 



Running random matrix example 2 of 5..

A-1B =
[[ 1.00000000e+00  3.33333333e-01 -5.55111512e-17]
 [-1.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.33333333e-01  0.00000000e+00]]
Could not calculate B-1A, continuing...
Could not calculate (AB)-1, continuing...
Could not calculate A-1*B-1, continuing...

 Completed matrix operations for matrices A and B! 



Runn

Quickly parse multiple choice solutions w/ copy & paste:
``` text
example pasted input "io.txt:"
text(0,0)
(1,-1)
(3,-1)
(-2,3)
(-1,1)
(-1,3)
(-3,2)
(2,-3)
```

In [11]:
# find matches to condition pasted in "io.txt"

from re import sub
def condition(x):
    avg = []
    if (.5* int(x[0])) + int(x[1]) <= 18:
        if int(x[1]) <= 16:
            if int(x[0]) <= 14:
                if int(x[0]) >= 0:
                    if int(x[1]) >= 0:
                        return True
                    else:
                        return False


def parse(fx, i=0):
    feasible = dict()
    def handler(ln):
        return sub('[()\n]', '', ln).split(',')
    with open('io.txt') as io:
        for ln in io:
            if fx(handler(ln)):
                result = [int(i) for i in handler(ln)]
                feasible[i] = result
                i += 1
    return feasible

# run: #
# print(parse(condition).values())