***Matrix operations with Numpy:***
- - -

*technology matrices:*      
"You are given a technology matrix A and an external demand vector D. Find the corresponding production vector X."

In [10]:
import numpy as np

def tMX(A,D):
    # (I - A-1) * B = X:
    return np.dot(np.linalg.inv(np.identity(len(A)) - A), D)

# example:
A = np.array([[.1, .5], [.1, .5]])
D = np.array([[22000], [14000]])
prodX = tMX(A, D)
#
print(str('production vector X = : \n' + str(prodX)))

production vector X = : 
[[45000.]
 [37000.]]


*matrix multiplication / operations with matrix inverse "I": *

In [11]:
import numpy as np

ex_A = np.array([[1,7],[-4,-26]])
ex_B = np.array([[1,-6],[5,-28]])

def matrix_ops(A=ex_A, B=ex_B):
    try:
        AinvB = np.dot(np.linalg.inv(A), B)
        print('A-1B =\n' + str(AinvB))
    except:
        print('Could not calculate A-1B')       
    try:
        BinvA = np.dot(np.linalg.inv(B), A)
        print('B-1A =\n' + str(BinvA))
    except:
        print('Could not calculate B-1A, continuing...')
    try:
        ABinv = np.linalg.inv(np.matmul(A,B))
        print('(AB)-1 =\n' + str(ABinv))
    except:
        print('Could not calculate (AB)-1, continuing...')
    try:
        AinvBinv = np.dot(np.linalg.inv(A), np.linalg.inv(B))
        print('A-1*B-1 =\n' + str(AinvBinv))
    except:
        print('Could not calculate A-1*B-1, continuing...')
    print('\n Completed matrix operations for matrices A and B! \n\n')

matrix_ops()  # using example values

A-1B =
[[-30.5 176. ]
 [  4.5 -26. ]]
B-1A =
[[ -26.  -176. ]
 [  -4.5  -30.5]]
(AB)-1 =
[[188.   50.5]
 [ 33.5   9. ]]
A-1*B-1 =
[[190.75 -40.75]
 [-29.25   6.25]]

 Completed matrix operations for matrices A and B! 




***more examples, testing w/ random matrices:***

In [12]:
def evalrandom():
    def randmat() : return np.random.randint(1,3,(3,3))
    for i in range(5):
        print(str('\nRunning random matrix example ' + str(i) + ' of 5..\n'))
        matrix_ops(randmat(), randmat()) 

# run with:
#evalrandom()

Quickly parsing multiple choice solutions w/ copy & paste:
``` text
Pasted input "io.txt:"
text(0,0)
(1,-1)
(3,-1)
(-2,3)
(-1,1)
(-1,3)
(-3,2)
(2,-3)
```

In [13]:
# find matches to condition pasted in "io.txt"
from re import sub
def condition(x):
    if int(x[1]) == 1-(2*int(x[0])):  # ensure inputs are numeric
        print(x)

def parse(fx):
    with open('io.txt') as io:
        for ln in io:
            fx(sub('[()\n]', '', ln).split(','))

# evaluate:
print('\n The following choices match condition(x):')
parse(condition) 


 The following choices match condition(x):
['1', '-1']
['-1', '3']
['2', '-3']
